# Generated by Django 4.2.18 on 2025-01-24 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pasApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="interviews",
        ),
        migrations.AddField(
            model_name="interview",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pasApp.product",
            ),
            preserve_default=False,
        ),
    ]
