# Generated by Django 4.2.18 on 2025-01-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default=1, upload_to="static/images"),
            preserve_default=False,
        ),
    ]
